### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by jonasstein** [paraenggu/delicious-absurdities-overlay#2]
Hi, your mail contact  in your gentoo packages does not work
`grep "c.affolter@" /usr/portage/*/*/*.xml`

please fix that and enter your valid contact 
please create a bugzilla account with the same valid contact
I could not assign bugs to you. https://bugs.gentoo.org/show_bug.cgi?id=630568
Thank you very much.

**Comment by paraenggu** [comment]
@jonasstein addressed within gentoo/gentoo#5679. The address of my bugzilla account was already changed, thanks for spotting it.

**Comment by jonasstein** [comment]
thank you
